name: resources
description: A new Flutter package project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter
  sprintf: 7.0.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults

flutter:
  assets:
    - lib/i18n/
    - lib/fonts/
    - assets/images/
    - assets/icons/
