name: analysis_defaults
description: Analysis defaults for project
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.19.5'

# NOTE: Code is not allowed in this package. Do not add dependencies.
dependencies:
  flutter_lints: 3.0.1
