name: analysis_defaults
description: Analysis defaults for project
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'

# NOTE: Code is not allowed in this package. Do not add dependencies.
dependencies:
  flutter_lints: 3.0.1
