name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  intl: 0.18.1
  sprintf: 7.0.0
  async: 2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_defaults:
    path: ../analysis_defaults

flutter:
