name: domain
description: A new Flutter package project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  data:
    path: ../data
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  get_it: ^7.7.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  youtube_explode_dart: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_defaults:
    path: ../analysis_defaults
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9

flutter:
