name: melodify
description: Music Player App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  cupertino_icons: 1.0.6
  connectivity_plus: 5.0.2
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  rxdart: 0.27.7
  firebase_core: 2.24.2
  firebase_messaging: 14.7.10
  firebase_crashlytics: 3.4.9
  devicelocale: 0.7.0
  flutter_svg: 2.0.9
  cached_network_image: 3.3.1
  flutter_dotenv: 5.1.0
  package_info: 2.0.2
  injectable: 2.3.2
  get_it: 7.6.7
  flutter_local_notifications: 16.3.1+1
  pinput: 3.0.1
  country_picker: 2.0.23
  path: 1.8.3
  path_provider: 2.1.2
  flutter_image_compress: 2.1.0
  image_picker: 1.0.7
  file_picker: 6.1.1
  audio_service: 0.18.12
  just_audio: 0.9.36
  audio_session: 0.1.18
  youtube_explode_dart: 2.1.0
  palette_generator: 0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_defaults:
    path: ../analysis_defaults
  injectable_generator: 2.4.1
  build_runner: 2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
  fonts:
    - family: 'Public Sans'
      fonts:
        - asset: packages/resources/fonts/public_sans/PublicSans-ExtraLight.ttf
          weight: 200
        - asset: packages/resources/fonts/public_sans/PublicSans-Light.ttf
          weight: 300
        - asset: packages/resources/fonts/public_sans/PublicSans-Regular.ttf
          weight: 400
        - asset: packages/resources/fonts/public_sans/PublicSans-Medium.ttf
          weight: 500
        - asset: packages/resources/fonts/public_sans/PublicSans-SemiBold.ttf
          weight: 600
        - asset: packages/resources/fonts/public_sans/PublicSans-Bold.ttf
          weight: 700
        - asset: packages/resources/fonts/public_sans/PublicSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-BoldItalic.ttf
          weight: 700
          style: italic
