name: melodify
description: Music Player App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  initializer:
    path: ../initializer
  resources:
    path: ../resources
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  firebase_crashlytics: ^3.5.5
  devicelocale: ^0.7.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  package_info: ^2.0.2
  injectable: ^2.4.1
  get_it: ^7.7.0
  flutter_local_notifications: ^17.1.2
  pinput: ^4.0.0
  country_picker: ^2.0.26
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_image_compress: ^2.2.0
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  audio_service: ^0.18.13
  just_audio: ^0.9.37
  audio_session: ^0.1.19
  youtube_explode_dart: ^2.2.1
  palette_generator: 0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_defaults:
    path: ../analysis_defaults
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
  fonts:
    - family: 'Public Sans'
      fonts:
        - asset: packages/resources/fonts/public_sans/PublicSans-ExtraLight.ttf
          weight: 200
        - asset: packages/resources/fonts/public_sans/PublicSans-Light.ttf
          weight: 300
        - asset: packages/resources/fonts/public_sans/PublicSans-Regular.ttf
          weight: 400
        - asset: packages/resources/fonts/public_sans/PublicSans-Medium.ttf
          weight: 500
        - asset: packages/resources/fonts/public_sans/PublicSans-SemiBold.ttf
          weight: 600
        - asset: packages/resources/fonts/public_sans/PublicSans-Bold.ttf
          weight: 700
        - asset: packages/resources/fonts/public_sans/PublicSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/resources/fonts/public_sans/PublicSans-BoldItalic.ttf
          weight: 700
          style: italic
